import {SuggestResponse} from '../../interface/route.interface';

export const mock: SuggestResponse = {
  location: {
    start: '스시진초밥',
    end: '서울 양천구 신정동 330',
  },
  stationInfo: {
    새절역: {
      lon: '126.913514',
      lat: '37.591164',
      stationId: '759059',
    },
    목동3단지: {
      lon: '126.875719',
      lat: '37.534694',
      stationId: '756198',
    },
    목동8단지_한전: {
      lon: '126.868383',
      lat: '37.520231',
      stationId: '755132',
    },
    신목동역_서울지방식품의약품안전청: {
      lon: '126.883253',
      lat: '37.543714',
      stationId: '756753',
    },
    목동2단지: {
      lon: '126.877986',
      lat: '37.536550',
      stationId: '756302',
    },
    목동4단지상가_목동종합운동장: {
      lon: '126.875086',
      lat: '37.532139',
      stationId: '756013',
    },
    목동7단지: {
      lon: '126.870275',
      lat: '37.528403',
      stationId: '755706',
    },
    역말사거리: {
      lon: '126.9151429014',
      lat: '37.6062104465',
      stationId: '111000119',
    },
    도착지: {
      lon: '126.86929166666667',
      lat: '37.51458888888889',
      stationId: null,
    },
    월촌중학교_목동1단지: {
      lon: '126.881653',
      lat: '37.537864',
      stationId: '756398',
    },
    양천구청: {
      lon: '126.866850',
      lat: '37.516514',
      stationId: '754837',
    },
    연서중학교입구: {
      lon: '126.911861',
      lat: '37.586194',
      stationId: '758899',
    },
    영등포아리수정수센터: {
      lon: '126.884036',
      lat: '37.547500',
      stationId: '756982',
    },
    마포농수산물시장_월드컵공원: {
      lon: '126.897336',
      lat: '37.566147',
      stationId: '758025',
    },
    신목동역: {
      lon: '126.881639',
      lat: '37.546039',
      stationId: '756890',
    },
    역촌오거리: {
      lon: '126.9239679445',
      lat: '37.6076554963',
      stationId: '111000167',
    },
    구산역3번출구_예일여고: {
      lon: '126.916776',
      lat: '37.610497',
      stationId: '111000118',
    },
    응암역2번출구: {
      lon: '126.9158607077',
      lat: '37.6004214787',
      stationId: '111000121',
    },
    신흥시장: {
      lon: '126.9145640351',
      lat: '37.5954014899',
      stationId: '111000080',
    },
    목1동주민센터: {
      lon: '126.873517',
      lat: '37.529806',
      stationId: '755811',
    },
    출발지: {
      lon: '126.93189200218671',
      lat: '37.61167139933952',
      stationId: null,
    },
    양천문화회관_양천일자리센터: {
      lon: '126.862400',
      lat: '37.516881',
      stationId: '754864',
    },
    월드컵경기장서측_문화비축기지: {
      lon: '126.894969',
      lat: '37.569403',
      stationId: '758192',
    },
    목동10단지상가: {
      lon: '126.859689',
      lat: '37.515958',
      stationId: '754811',
    },
    목동12단지: {
      lon: '126.860556',
      lat: '37.514344',
      stationId: '754698',
    },
    대조시장: {
      lon: '126.926162',
      lat: '37.608786',
      stationId: '111000166',
    },
    응암역_신사오거리: {
      lon: '126.9152247795',
      lat: '37.5979358249',
      stationId: '111000079',
    },
    목동13단지: {
      lon: '126.86929166666667',
      lat: '37.51458888888889',
      stationId: null,
    },
    와산교: {
      lon: '126.912750',
      lat: '37.587925',
      stationId: '758947',
    },
    삼성타운: {
      lon: '126.9209709958',
      lat: '37.6087032927',
      stationId: '111000051',
    },
    불광역4번출구: {
      lon: '126.930336',
      lat: '37.609758',
      stationId: '111000034',
    },
    양천구청_양천보건소: {
      lon: '126.866253',
      lat: '37.518217',
      stationId: '754955',
    },
    증산종합시장_증산중학교입구: {
      lon: '126.906167',
      lat: '37.580792',
      stationId: '758690',
    },
    양천구민체육센터_양천일자리센터: {
      lon: '126.864328',
      lat: '37.515647',
      stationId: '754788',
    },
    하이스트학원_종로학원: {
      lon: '126.869508',
      lat: '37.524953',
      stationId: '755470',
    },
    증산역_증산동주민센터: {
      lon: '126.909364',
      lat: '37.583800',
      stationId: '758818',
    },
    역촌초등학교: {
      lon: '126.9155726294',
      lat: '37.6027929337',
      stationId: '111000120',
    },
    양광교회: {
      lon: '126.9289518591',
      lat: '37.6085452704',
      stationId: '111000165',
    },
    역촌역_역촌오거리: {
      lon: '126.9224758463',
      lat: '37.606957085',
      stationId: '111000050',
    },
  },
  infoList: [
    {
      summary: {
        taxiFare: 14200,
        wastedTime: 3743,
        savedTime: 1237,
        savedMoney: 7300,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 1958,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '신목동역-서울지방식품의약품안전청'],
        },
        {
          mode: 'BUS',
          sectionTime: 1740,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 14000,
        wastedTime: 3746,
        savedTime: 1234,
        savedMoney: 7500,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 1901,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '신목동역'],
        },
        {
          mode: 'BUS',
          sectionTime: 1920,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 15800,
        wastedTime: 3766,
        savedTime: 1214,
        savedMoney: 5700,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 2281,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '목동2단지'],
        },
        {
          mode: 'BUS',
          sectionTime: 1500,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 16200,
        wastedTime: 3796,
        savedTime: 1184,
        savedMoney: 5300,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 2371,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '목동3단지'],
        },
        {
          mode: 'BUS',
          sectionTime: 1380,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 15500,
        wastedTime: 3811,
        savedTime: 1169,
        savedMoney: 6000,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 2206,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '월촌중학교.목동1단지'],
        },
        {
          mode: 'BUS',
          sectionTime: 1680,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 9300,
        wastedTime: 4236,
        savedTime: 744,
        savedMoney: 12200,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 1251,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '증산역.증산동주민센터'],
        },
        {
          mode: 'BUS',
          sectionTime: 3000,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 9900,
        wastedTime: 4208,
        savedTime: 772,
        savedMoney: 11600,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 1343,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '증산종합시장.증산중학교입구'],
        },
        {
          mode: 'BUS',
          sectionTime: 2880,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 17700,
        wastedTime: 3878,
        savedTime: 1102,
        savedMoney: 3800,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 2633,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '목1동주민센터'],
        },
        {
          mode: 'BUS',
          sectionTime: 1260,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 17200,
        wastedTime: 3897,
        savedTime: 1083,
        savedMoney: 4300,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 2532,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '목동4단지상가.목동종합운동장'],
        },
        {
          mode: 'BUS',
          sectionTime: 1320,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 12400,
        wastedTime: 4230,
        savedTime: 750,
        savedMoney: 9100,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 1845,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '마포농수산물시장.월드컵공원'],
        },
        {
          mode: 'BUS',
          sectionTime: 2400,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 9000,
        wastedTime: 4294,
        savedTime: 686,
        savedMoney: 12500,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 1189,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '연서중학교입구'],
        },
        {
          mode: 'BUS',
          sectionTime: 3060,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 7700,
        wastedTime: 4297,
        savedTime: 683,
        savedMoney: 13800,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 892,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '신흥시장'],
        },
        {
          mode: 'BUS',
          sectionTime: 3360,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '신흥시장',
            '새절역',
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 8900,
        wastedTime: 4314,
        savedTime: 666,
        savedMoney: 12600,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 1149,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '와산교'],
        },
        {
          mode: 'BUS',
          sectionTime: 3180,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 7500,
        wastedTime: 4326,
        savedTime: 654,
        savedMoney: 14000,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 861,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '응암역.신사오거리'],
        },
        {
          mode: 'BUS',
          sectionTime: 3480,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '응암역.신사오거리',
            '신흥시장',
            '새절역',
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 8400,
        wastedTime: 4329,
        savedTime: 651,
        savedMoney: 13100,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 1044,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '새절역'],
        },
        {
          mode: 'BUS',
          sectionTime: 3300,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '새절역',
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 7000,
        wastedTime: 4336,
        savedTime: 644,
        savedMoney: 14500,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 751,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '응암역2번출구'],
        },
        {
          mode: 'BUS',
          sectionTime: 3600,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '응암역2번출구',
            '응암역.신사오거리',
            '신흥시장',
            '새절역',
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 15100,
        wastedTime: 3848,
        savedTime: 1132,
        savedMoney: 6400,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 1823,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '영등포아리수정수센터'],
        },
        {
          mode: 'BUS',
          sectionTime: 2280,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 13900,
        wastedTime: 4573,
        savedTime: 407,
        savedMoney: 7600,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 2068,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '월드컵경기장서측.문화비축기지'],
        },
        {
          mode: 'BUS',
          sectionTime: 2760,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 7300,
        wastedTime: 4481,
        savedTime: 499,
        savedMoney: 14200,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 776,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '역촌초등학교'],
        },
        {
          mode: 'BUS',
          sectionTime: 3840,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '역촌초등학교',
            '응암역2번출구',
            '응암역.신사오거리',
            '신흥시장',
            '새절역',
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 7800,
        wastedTime: 4812,
        savedTime: 168,
        savedMoney: 13700,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 867,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '역말사거리'],
        },
        {
          mode: 'BUS',
          sectionTime: 3960,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '역말사거리',
            '역촌초등학교',
            '응암역2번출구',
            '응암역.신사오거리',
            '신흥시장',
            '새절역',
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 7100,
        wastedTime: 4914,
        savedTime: 66,
        savedMoney: 14400,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 849,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '구산역3번출구.예일여고'],
        },
        {
          mode: 'BUS',
          sectionTime: 120,
          route: '마을:은평04',
          routeId: '111900004',
          stationList: ['구산역3번출구.예일여고'],
        },
        {
          mode: 'BUS',
          sectionTime: 3960,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '구산역3번출구.예일여고',
            '역말사거리',
            '역촌초등학교',
            '응암역2번출구',
            '응암역.신사오거리',
            '신흥시장',
            '새절역',
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 6400,
        wastedTime: 4752,
        savedTime: 228,
        savedMoney: 15100,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 567,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '삼성타운'],
        },
        {
          mode: 'BUS',
          sectionTime: 180,
          route: '마을:은평04',
          routeId: '111900004',
          stationList: ['삼성타운', '구산역3번출구.예일여고'],
        },
        {
          mode: 'BUS',
          sectionTime: 3960,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '구산역3번출구.예일여고',
            '역말사거리',
            '역촌초등학교',
            '응암역2번출구',
            '응암역.신사오거리',
            '신흥시장',
            '새절역',
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 5000,
        wastedTime: 4681,
        savedTime: 299,
        savedMoney: 16500,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 316,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '대조시장'],
        },
        {
          mode: 'BUS',
          sectionTime: 420,
          route: '마을:은평04',
          routeId: '111900004',
          stationList: [
            '대조시장',
            '역촌오거리',
            '역촌역.역촌오거리',
            '삼성타운',
            '구산역3번출구.예일여고',
          ],
        },
        {
          mode: 'BUS',
          sectionTime: 3960,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '구산역3번출구.예일여고',
            '역말사거리',
            '역촌초등학교',
            '응암역2번출구',
            '응암역.신사오거리',
            '신흥시장',
            '새절역',
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 5500,
        wastedTime: 4715,
        savedTime: 265,
        savedMoney: 16000,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 410,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '역촌오거리'],
        },
        {
          mode: 'BUS',
          sectionTime: 300,
          route: '마을:은평04',
          routeId: '111900004',
          stationList: [
            '역촌오거리',
            '역촌역.역촌오거리',
            '삼성타운',
            '구산역3번출구.예일여고',
          ],
        },
        {
          mode: 'BUS',
          sectionTime: 3960,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '구산역3번출구.예일여고',
            '역말사거리',
            '역촌초등학교',
            '응암역2번출구',
            '응암역.신사오거리',
            '신흥시장',
            '새절역',
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 6000,
        wastedTime: 4746,
        savedTime: 234,
        savedMoney: 15500,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 501,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '역촌역.역촌오거리'],
        },
        {
          mode: 'BUS',
          sectionTime: 240,
          route: '마을:은평04',
          routeId: '111900004',
          stationList: [
            '역촌역.역촌오거리',
            '삼성타운',
            '구산역3번출구.예일여고',
          ],
        },
        {
          mode: 'BUS',
          sectionTime: 3960,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '구산역3번출구.예일여고',
            '역말사거리',
            '역촌초등학교',
            '응암역2번출구',
            '응암역.신사오거리',
            '신흥시장',
            '새절역',
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 5200,
        wastedTime: 4868,
        savedTime: 112,
        savedMoney: 16300,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 383,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '양광교회'],
        },
        {
          mode: 'BUS',
          sectionTime: 480,
          route: '마을:은평04',
          routeId: '111900004',
          stationList: [
            '양광교회',
            '대조시장',
            '역촌오거리',
            '역촌역.역촌오거리',
            '삼성타운',
            '구산역3번출구.예일여고',
          ],
        },
        {
          mode: 'BUS',
          sectionTime: 3960,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '구산역3번출구.예일여고',
            '역말사거리',
            '역촌초등학교',
            '응암역2번출구',
            '응암역.신사오거리',
            '신흥시장',
            '새절역',
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
    {
      summary: {
        taxiFare: 4800,
        wastedTime: 4829,
        savedTime: 151,
        savedMoney: 16700,
      },
      steps: [
        {
          mode: 'TAXI',
          sectionTime: 284,
          route: null,
          routeId: null,
          stationList: ['스시진초밥', '불광역4번출구'],
        },
        {
          mode: 'BUS',
          sectionTime: 480,
          route: '마을:은평04',
          routeId: '111900004',
          stationList: [
            '불광역4번출구',
            '양광교회',
            '대조시장',
            '역촌오거리',
            '역촌역.역촌오거리',
            '삼성타운',
            '구산역3번출구.예일여고',
          ],
        },
        {
          mode: 'BUS',
          sectionTime: 3960,
          route: '간선:571',
          routeId: '100100084',
          stationList: [
            '구산역3번출구.예일여고',
            '역말사거리',
            '역촌초등학교',
            '응암역2번출구',
            '응암역.신사오거리',
            '신흥시장',
            '새절역',
            '와산교',
            '연서중학교입구',
            '증산역.증산동주민센터',
            '증산종합시장.증산중학교입구',
            '월드컵경기장서측.문화비축기지',
            '마포농수산물시장.월드컵공원',
            '영등포아리수정수센터',
            '신목동역',
            '신목동역-서울지방식품의약품안전청',
            '월촌중학교.목동1단지',
            '목동2단지',
            '목동3단지',
            '목동4단지상가.목동종합운동장',
            '목1동주민센터',
            '목동7단지',
            '하이스트학원.종로학원',
            '목동8단지.한전',
            '양천구청.양천보건소',
            '양천문화회관.양천일자리센터',
            '목동10단지상가',
            '목동12단지',
            '양천구민체육센터.양천일자리센터',
            '양천구청',
            '목동13단지',
          ],
        },
        {
          mode: 'WALK',
          sectionTime: 317,
          route: null,
          routeId: null,
          stationList: ['목동13단지', '서울 양천구 신정동 330'],
        },
      ],
    },
  ],
};
